export const SAMPLE_PRODUCTS = [
  {
    id: '1',
    sku: 'SKU001',
    img: 'https://via.placeholder.com/200',
    title: 'Sample Product One',
    slug: 'sample-product-one',
    unit: 'pcs',
    imageURLs: [{ img: 'https://via.placeholder.com/400' }],
    parent: 'root',
    children: 'sample-product',
    price: 29.99,
    discount: 0,
    quantity: 10,
    brand: { name: 'BrandX' },
    category: { name: 'General' },
    status: 'available',
    productType: 'default',
    description: 'A great sample product to showcase our shop.',
    additionalInformation: [],
    sellCount: 0,
  },
  {
    id: '2',
    sku: 'SKU002',
    img: 'https://via.placeholder.com/200',
    title: 'Sample Product Two',
    slug: 'sample-product-two',
    unit: 'pcs',
    imageURLs: [{ img: 'https://via.placeholder.com/400' }],
    parent: 'root',
    children: 'sample-product',
    price: 49.99,
    discount: 10,
    quantity: 5,
    brand: { name: 'BrandY' },
    category: { name: 'General' },
    status: 'available',
    productType: 'default',
    description: 'Another fantastic item in our inventory.',
    additionalInformation: [],
    sellCount: 0,
  },
  {
    id: '3',
    sku: 'SKU003',
    img: 'https://via.placeholder.com/200',
    title: 'Sample Product Three',
    slug: 'sample-product-three',
    unit: 'pcs',
    imageURLs: [{ img: 'https://via.placeholder.com/400' }],
    parent: 'root',
    children: 'sample-product',
    price: 19.99,
    discount: 0,
    quantity: 20,
    brand: { name: 'BrandZ' },
    category: { name: 'General' },
    status: 'available',
    productType: 'default',
    description: 'A budget friendly product for everyday use.',
    additionalInformation: [],
    sellCount: 0,
  },
];
