export const SAMPLE_PRODUCTS = [
  {
    id: '1',
    sku: 'SKU001',
    img: 'https://i.ibb.co/WVdTgR8/headphone-1.png',
    title: 'Sample Product One',
    slug: 'sample-product-one',
    unit: 'pcs',
    imageURLs: [
      { img: 'https://i.ibb.co/WVdTgR8/headphone-1.png' },
      { img: 'https://i.ibb.co/zh9x3Q0/headphone-2.png' },
      { img: 'https://i.ibb.co/JBZk7sS/headphone-3.png' },
      { img: 'https://i.ibb.co/SrPq3r0/headphone-4.png' },
    ],
    parent: 'root',
    children: 'sample-product',
    price: 29.99,
    discount: 0,
    quantity: 10,
    brand: { name: 'BrandX' },
    category: { name: 'General' },
    status: 'available',
    productType: 'default',
    description: 'A great sample product to showcase our shop.',
    additionalInformation: [],
    sellCount: 0,
  },
  {
    id: '2',
    sku: 'SKU002',
    img: 'https://i.ibb.co/n1YRvWJ/headphone-5.png',
    title: 'Sample Product Two',
    slug: 'sample-product-two',
    unit: 'pcs',
    imageURLs: [
      { img: 'https://i.ibb.co/n1YRvWJ/headphone-5.png' },
      { img: 'https://i.ibb.co/WpkH1vq/headphone-6.png' },
      { img: 'https://i.ibb.co/yRYbDCc/headphone-7.png' },
    ],
    parent: 'root',
    children: 'sample-product',
    price: 49.99,
    discount: 10,
    quantity: 5,
    brand: { name: 'BrandY' },
    category: { name: 'General' },
    status: 'available',
    productType: 'default',
    description: 'Another fantastic item in our inventory.',
    additionalInformation: [],
    sellCount: 0,
  },
  {
    id: '3',
    sku: 'SKU003',
    img: 'https://i.ibb.co/5FPhGtq/headphone-8.png',
    title: 'Sample Product Three',
    slug: 'sample-product-three',
    unit: 'pcs',
    imageURLs: [
      { img: 'https://i.ibb.co/5FPhGtq/headphone-8.png' },
      { img: 'https://i.ibb.co/vHP1TQf/headphone-9.png' },
      { img: 'https://i.ibb.co/3mdtrcm/headphone-10.png' },
    ],
    parent: 'root',
    children: 'sample-product',
    price: 19.99,
    discount: 0,
    quantity: 20,
    brand: { name: 'BrandZ' },
    category: { name: 'General' },
    status: 'available',
    productType: 'default',
    description: 'A budget friendly product for everyday use.',
    additionalInformation: [],
    sellCount: 0,
  },
];
