name: CI

on:
  push:
    branches:
      - main

jobs: 
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      - name: Build and deploy
        run: |
          npm install --force
          npm run build
