name: CI

on:
  push:
    branches:
      - main

jobs: 
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts


      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      - name: Build and deploy
        run: |
          npm install --force
          npm run build
