name: CI

on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
          remote: true

     # - name: Initialize and update submodules
      #  run: |
      #    git config submodule.src/app/authorization.url git@github.com:jihadelsayed/authorization.git
       #   git config submodule.src/app/header.url git@github.com:jihadelsayed/header.git
       #   git config submodule.src/app/not-found.url git@github.com:jihadelsayed/not-found.git
        #  git submodule update --init --recursive

    - name: Initialize and update submodules
      run: |
        git submodule init
        git submodule update

    - name: Build and deploy
      run: |
        npm install --force
        npm run build
