name: CI
on:
  push:
    branches:
    - main
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      - name: Build and deploy authorization submodule
        working-directory: src/app/authorization
        run: |
          npm install
          npm run build
          # Add deployment commands specific to the authorization submodule

      - name: Build and deploy not-found submodule
        working-directory: src/app/not-found
        run: |
          npm install
          npm run build
          # Add deployment commands specific to the not-found submodule

      - name: Build and deploy header submodule
        working-directory: src/app/header
        run: |
          npm install
          npm run build
          # Add deployment commands specific to the header submodule
