name: CI

on:
  push:
    branches:
      - main
       
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      - name: Build and deploy
        run: |
          npm install --force
          npm run build
